tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

brew 'hub'
brew 'coreutils'
brew 'exa'
brew 'bat'
brew 'stow'
brew 'git'
brew 'jq'
brew 'vim'
brew 'python'
brew 'python3'
brew 'bash'
brew 'bash-completion2'
brew 'imagemagick', args: ["with-webp"]
brew 'lua'
brew 'tree'
brew 'libxml2'
brew 'libxslt'
brew 'sleepwatcher'

cask 'alfred'
cask 'sublime-text'
cask 'atom'
cask 'evernote'
cask 'gimp'
# cask 'inkscape'
# cask 'iterm2'
cask 'firefox'
cask 'macvim'
cask 'shiftit'
cask 'font-hack'
cask 'font-hack-nerd-font'

cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlimagesize'

mas 'onenote', id: 784801555
mas 'whatsapp', id: 1147396723
