tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'jeantil/autokbisw'
tap 'homebrew/cask-drivers'

brew 'hub'
brew 'coreutils'
brew 'exa'
brew 'bat'
brew 'stow'
brew 'git'
brew 'jq'
brew 'vim'
brew 'bash'
brew 'bash-completion2'
brew 'imagemagick'
brew 'lua'
brew 'tree'
brew 'libxml2'
brew 'libxslt'
brew 'sleepwatcher'
brew "jeantil/autokbisw/autokbisw", start_service: true
brew 'htop'
brew 'pstree'
brew 'thefuck'
brew 'the_silver_searcher'

cask 'alfred'
cask 'atom'
cask 'blender'
cask 'font-hack'
cask 'font-hack-nerd-font'
cask 'gimp'
cask 'kindle'
cask 'sonos'
cask 'wireshark'

cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlimagesize'

mas 'onenote', id: 784801555
